### ISSUE TITLE
babel-plugin-transform-es2015-duplicate-keys plugin is lost

### ISSUE THREAD

**Issue by YuJianrong** [Collaborne/babel-preset-es2015-script#1]
```babel-plugin-transform-es2015-duplicate-keys``` plugin is not included in the preset, cause the es6 code:
```
"use strict";
let a= {
  a:1,
  a:1
}
```
compile to 
```
"use strict";
var a= {
  a:1,
  a:1
}
```
which is not a valid ES5 code. The code should be compile to :
```
"use strict";

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

var a = _defineProperty({
  a: 1
}, "a", 1);
```

**Comment by ankon** [comment]
Thanks for the report. I missed adding the plugin reference when I updated to the newest preset.

This should be fixed in version 1.1.1, but please note that you can actually achieve the same goals that this preset tried to achieve using the upstream preset. Replace
```js
{
  "presets": [ "es2015-script" ]
}
```
with
```js
{
  "presets": [ [ "es2015", { modules: false } ] ]
}
```
